name: CI Pipeline

on:
  push:
    branches: 
      - '*'

jobs:
  build-and-lint:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint lint --config swiftlint.yml

    - name: Build App
      run: xcodebuild build -schema Pokedex
